### ISSUE TITLE
Apply Categories to Named Individuals

### ISSUE THREAD

**Issue by ccondit** [SciCrunch/SciGraph#73]
How should categories be applied to named individuals. Is there a better method than the current simple scheme?

**Comment by nlwashington** [comment]
in this example:
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genotypes_from_gene.json?gene_id=ZDB-GENE-070117-1709

the sequence alteration ZDB-ALT-061101-19 is a named individual that doesn't have a category.  i am not even sure we want to give it a category.  

same for ZDB-GENO-061101-19, it is also a named individual (i believe of type intrinsic_genotype).  

since all individuals are typed as some class in the graph, should we just expose the actual type that the thing is, without having to "categorize" it?  and then if it is an instance of a node that is categorized, it would include that.  for example, by adding a "type" to the node, like:
<pre> 
{
  "id": "ZDB-GENO-061101-19",
  "lbl": "unm_t31392<sup>t31392</sup>",
  "type" : "GENO:0000000"              # added "type" here
  "meta":
    {
        "category": [ ]
    }
}
</pre>
in this example, intrinsic_genotypes are not categorized, so it wouldn't have one.  but in the case of a gene, it might have:
<pre>
{
    "id": "ZDB-GENE-070117-1709",
    "lbl": "unm_t31392",
    "type" : "SO:0001217"        #where the term is the specific type: protein_coding_gene
    "meta": 
      {
        "category":  [ "gene" ]
      }
}, </pre>
