### ISSUE TITLE
Use DIPPER mapping format for CURIEs

### ISSUE THREAD

**Issue by ccondit** [SciCrunch/SciGraph#80]
Should read: 

    prefix : IRI prefix

and update the location for all the build plans.

**Comment by nlwashington** [comment]
here's the current yaml configuration used for dipper:
https://raw.githubusercontent.com/monarch-initiative/dipper/master/dipper/curie_map.yaml

**Comment by nlwashington** [comment]
will this be an issue?
'ISBN-10': 'http://www.monarchinitiative.org/ISBN_'
'ISBN-13': 'http://www.monarchinitiative.org/ISBN_'
'ISBN-15': 'http://www.monarchinitiative.org/ISBN_'
'ISBN': 'http://www.monarchinitiative.org/ISBN_'

basically the data i have uses those ISBN prefixes in their annotations, but i map them to simply ISBN because i don't think they clobber one another.

**Comment by cmungall** [comment]
We decided to retain the numeric portion, e.g. ISBN10

Since we're discussing this, might be a good idea to have a strategy to make sure all things that point to us are resolvable. E.g. http://monarchinitiative.org/object/CURIE

**Comment by ccondit** [comment]
@nlwashington will these mappings from dipper be usable for monarch.owl as well?

**Comment by ccondit** [comment]
This has been redeployed with the new CURIEs on geoffrey and rosie.
